name: Trigger auto deployment for dev-pyproject-yourworkername

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/dev-pyproject-yourworkername-AutoDeployTrigger-489ce278-c460-42af-943f-e608949f7c7b.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DEVPYPROJECTYOURWORKERNAME_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: ca0d53ab6198acr.azurecr.io
          registryUsername: ${{ secrets.DEVPYPROJECTYOURWORKERNAME_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DEVPYPROJECTYOURWORKERNAME_REGISTRY_PASSWORD }}
          containerAppName: dev-pyproject-yourworkername
          resourceGroup: deploytest
          imageToBuild: ca0d53ab6198acr.azurecr.io/dev-pyproject-yourworkername:${{ github.sha }}
          
            

     

